import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'

import { mediaUrl } from '../utils/fetchData'
import clientPromise from '../lib/mongodb'
import Navbar from './components/Navbar'
import { useSession } from 'next-auth/react'
import Login from './components/Login'
import Footer from './components/Footer'

export const getStaticProps = async () => {
  const client = await clientPromise;
  const db = client.db("Instacats");

  const posts = await db
    .collection("posts")
    .find({})
    .limit(1000)
    .toArray();
  return {
    props: { posts: JSON.parse(JSON.stringify(posts)) },
  };
}

export default function Home({ posts }) {
  const { data: session } = useSession()
  const [slice, setSlice] = useState(9)
  const [postsArr, setPostsArr] = useState(posts)
  const [userImage, setUserImage] = useState(false)

  if (!session) {
    return (
      <Login />
    )
  }

  // set user post to first position
  const setImage = async () => {
    const index = postsArr.findIndex(post => post.name === session?.user.name)
    postsArr[0] = postsArr[index]
    setUserImage(true)
    console.log(index)
  }

  return (
    <div className='bg-black'>
      <Head>
        <title>Instacats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className='mt-10'>
        <ul className='flex flex-wrap justify-evenly'>
          {postsArr.slice(0, slice).map(post => (
            <li className='w-[20rem] mb-10 border border-gray-500 p-2 rounded' key={post.timestamp_created}>
              <Link href={`/image/${post.image}`}>
                <Image
                  src={`${mediaUrl}/media/${post.image}`}
                  width='400'
                  height='400'
                  alt='Cat Picture'
                  priority
                />
                <p className='overflow-hidden text-white'>Name: {post.name}</p>
                <p className='text-white'>Posted: {post.timestamp_created}</p>
                <p className='text-white'>By: {post.pk}</p>
              </Link>
            </li>
          ))}
        </ul>
      </main>
      {slice > 9 && (
        <div className='text-white text-center mb-5'>
          <button className='border border-red-800 px-2 py-1 rounded hover:bg-red-800' onClick={() => setSlice(9)}>View Less</button>
        </div>
      )}
      <div className='text-white text-center mb-5'>
        <button className='border border-red-800 px-2 py-1 rounded hover:bg-red-800' onClick={() => setSlice(slice * 2)}>View More</button>
      </div>
      <Footer />
    </div>
  )
}