import React from 'react'
import { signIn } from 'next-auth/react'
import Head from 'next/head'
import Footer from './Footer'

const Login = () => {
    return (
        <div className='bg-black h-[100vh] flex flex-col justify-center'>
            <Head>
                <title>Instacats</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className='text-center h-[20rem] flex flex-col justify-center mx-auto p-5'>
                <p className='text-3xl text-white'>You need to login first!</p>
                <button className='bg-white rounded p-2 mt-4 hover:bg-red-800' onClick={() => signIn()}>Log In</button>
            </main>
            <Footer />
        </div>
    )
}

export default Login